services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spotter-prod
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./storage:/var/www/html/storage
      - public-build:/var/www/html/public
    depends_on:
      - mysql
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - public-build:/var/www/html/public:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/letsencrypt:/etc/letsencrypt:ro
      - certbot-htdocs:/var/www/certbot
    depends_on:
      - app
    networks:
      - appnet

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-prod-data:/var/lib/mysql
    networks:
      - appnet

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/letsencrypt:/etc/letsencrypt
      - certbot-htdocs:/var/www/certbot
    entrypoint: ""
    command: sleep infinity
    profiles: [ "certbot" ]

  nginx-certbot:
    image: nginx:alpine
    container_name: nginx-certbot
    ports:
      - "80:80"
    volumes:
      - ./nginx.certbot.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-htdocs:/var/www/certbot
    command: >
      sh -c "mkdir -p /var/www/certbot/.well-known &&
             nginx -g 'daemon off;'"
    profiles: [ "certbot" ]

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - appnet

networks:
  appnet:


volumes:
  mysql-prod-data:
  certbot-htdocs:
  public-build:
