<?php

use App\Models\User;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('ai_requests', function (Blueprint $table) {
            $table->id();
            $table->string('meta_id', 64)->nullable()->comment('UUID from AI provider to track request (e.g. OpenAI response ID)');
            $table->uuid('request_uuid')->unique()->comment('UUID for tracking the request across systems (generated by client)');
            $table->foreignIdFor(User::class);
            $table->string('caller_class', 64)->comment('Caller class that initiated the AI request');
            $table->string('ai_model', 32)->comment('AI model name (e.g. gpt-5-mini)');
            $table->string('provider', 32)->comment('AI provider name (e.g. openai)');

            $table->string('schema_version', 32)->nullable()->comment('Schema version');
            $table->string('schema_hash', 64)->nullable()->comment('Hash fingerprint of schema version contents');
            $table->string('prompt_version', 32)->comment('Prompt version');
            $table->string('system_prompt_version', 32)->comment('System prompt version');

            $table->json('user_input_json')->nullable()->comment('User input preferences payload');
            $table->string('operation_key')->nullable()->comment('Operation context key (e.g. mesocycle_create)');
            $table->string('finish_reason')->nullable()->comment('Finish reason from AI response');
            $table->integer('latency_ms')->nullable()->comment('Request latency in milliseconds');

            $table->integer('prompt_tokens')->nullable();
            $table->integer('completion_tokens')->nullable();
            $table->integer('total_tokens')->nullable();
            $table->json('usage_json')->nullable()->comment('Usage metadata from AI response');

            $table->json('output_json')->nullable()->comment('Raw AI response payload (typically for failed requests)');
            $table->string('error_class')->nullable();
            $table->string('error_message')->nullable();
            $table->string('error_stage')->nullable();
            $table->string('status', 16);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('ai_requests');
    }
};
