services:
  app:
    # Testing ci / cd on local
    # build:
    #   context: ../../
    #   dockerfile: Dockerfile
    # image: ci-image:dev
    image: ${IMAGE}@${DIGEST}
    pull_policy: always
    env_file:
      - .env.ci                 # this stays (process env vars)
    working_dir: /var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      # - ../../:/var/www/html
      - vendor-ci:/var/www/html/vendor
      - type: bind
        source: ./.env.ci
        target: /var/www/html/.env
        read_only: true
      - type: bind
        source: ./.env.ci
        target: /var/www/html/.env.testing
        read_only: true
    networks: [ci_net]

  mysql:
    image: mysql:8.4
    platform: linux/amd64
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-log-bin
      - --skip-name-resolve
      - --innodb-buffer-pool-size=128M
      - --max-connections=50
      - --performance-schema=OFF
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: testing
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: ci_pass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-psecret"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
    networks: [ci_net]

networks:
  ci_net: {}

volumes:
  mysql_data: {}
  vendor-ci: {}
