services:
  app:
    build:
      context: ../../
      dockerfile: ./docker/ci/Dockerfile.ci
    image: spotter-ci
    env_file:
      - .env.ci
    depends_on:
      mysql:
        condition: service_healthy
    networks: [ci_net]
    # no ports in CI
    # if you want to wait for DB right here, uncomment:
    # command: >
    #   sh -lc '
    #     for i in $(seq 1 60); do
    #       php -r "try{new PDO(\"mysql:host=mysql;port=3306;dbname=${DB_DATABASE}\",\"${DB_USERNAME}\",\"${DB_PASSWORD}\");exit(0);}catch(Throwable $e){exit(1);}"; rc=$?; [ $rc -eq 0 ] && break; sleep 1;
    #     done;
    #     php -v
    #   '

  mysql:
    image: mysql:8.4
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-log-bin
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: testing
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: ci_pass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-pci_pass", "-uci_user"]
      interval: 5s
      timeout: 3s
      retries: 20
    # super fast ephemeral storage in CI:
    tmpfs:
      - /var/lib/mysql
    networks: [ci_net]

networks:
  ci_net: {}
