name: Validation Pipeline

on:
    pull_request:
        branches:
            - main
            - prod
    push:
        branches:
            - tests/*

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-24.04

        steps:
            - name: Pull the current branch
              uses: actions/checkout@v7

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4

            - name: Build image with cache
              uses: docker/build-push-action@v7
              with:
                  context: .
                  load: true
                  tags: spotacus:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - run: docker image ls

            - name: Boot that mf up and stop it after
              run: |
                  docker run --rm spotacus:latest
                  sleep 5
                  docker ps
                  docker logs spotacus:latest
                  docker stop spotacus:latest

            # checkout the repo current branch

            # build the image

            # login to a registry

            # push it to a registry

            # get the tags to identify the build image

    # test:
    # login to a registry again

    # pull the image

    # run it

    # start testing it
